=== Eeemil/scale.cloudpool/commons/src/main/resources/baseadapter-schema.json
{
  "id": "http://elastisys.com/baseadapter-schema#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "configuration schema for a generic cloud adapter",
  "type": "object",
  "properties": {
    "scalingGroup": {
      "description": "Describes how the ScalingGroup implementation identifies/manages scaling group members and connects to its cloud provider.", 
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the logical group of servers managed by the ScalingGroup.", 
          "type": "string"
        },
        "config": {
          "description": "ScalingGroup-specific JSON configuration document, the contents of which depends on the particular ScalingGroup-implementation being used. Typically, a minimum amount of configuration includes login credentials for connecting to the particular cloud API endpoint.",
          "type": "object"
        }
      },
      "required": ["name", "config"]
    },
    "scaleUpConfig": { 
      "description": "Describes how to provision additional servers (on scale-up).", 
      "type": "object",
      "properties": {
        "size": {
          "description": "The name of the server type to launch. For example, m1.medium.", 
          "type":  "string"
        },
        "image": {
          "description": "The name of the machine image used to boot new servers.", 
          "type":  "string" 
        },
        "keyPair": {
          "description": "The name of the key pair to use for new machine instances.", 
          "type":  "string" 
        },
        "securityGroups": {
          "description": "The security group(s) to use for new machine instances.", 
          "type":  "array",
          "items": { "type": "string" }
        },
        "bootScript": {
          "description": "The script to run after first boot of a new instance.",
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["size", "image", "keyPair", "securityGroups", "bootScript"] 
    },
    "scaleDownConfig": { 
      "description": "Describes how to decommission servers (on scale-down).", 
      "type": "object",
      "properties": {
        "victimSelectionPolicy": {
          "description": "Policy for selecting which server to terminate.", 
          "enum":  ["NEWEST_INSTANCE", "OLDEST_INSTANCE", "CLOSEST_TO_INSTANCE_HOUR"] 
        },
        "instanceHourMargin": {
          "description": "How many seconds prior to the next instance hour an acquired machine instance should be scheduled for termination. This should be set to a conservative and safe value to prevent the machine from being billed for an additional hour. A value of zero is used to specify immediate termination when a scale-down is ordered.",
          "type": "number"
        }
      },
      "required": ["victimSelectionPolicy", "instanceHourMargin"]
    },
    "liveness": {
      "description": "Optional configuration that determines how to monitor the liveness of scaling group members. If left out, liveness checking is disabled.",
      "type": "object",
      "properties": {
        "sshPort": {
          "description": "The SSH port to connect to on machines in the scaling group. Defaults to 22.",
          "type": "number"
        },
        "loginUser": {
          "description": "The user name to use (together with the 'loginKey' when logging in remotely (over SSH) against machines in the scaling group.", 
          "type": "string"
        },
        "loginKey": {  
          "description": "The path to the private key file of the key pair used to launch new machine instances in the Auto Scaling group. This key is used to log in remotely (over SSH) against machines in the scaling group.", 
          "type": "string"
        },
        "bootTimeCheck": {
          "description": "Configuration for boot-time liveness tests, which wait for a server to come live when a new server is provisioned in the scaling group.",
          "type": "object",
          "properties": {
            "command": {
              "description": "The command/script (executed over SSH) used to determine when a booting machine is up and running. A machine instance is considered live when the command is successful (zero exit code).",
              "type": "string"
            },
            "maxRetries": {
              "description": "The maximum number of attempts to run the liveness test before failing.",
              "type": "number",
              "minimum": 0
            },
            "retryDelay": {
              "description": "The delay (in seconds) between two successive liveness command retries.",
              "type": "number",
              "minimum": 0
            }
          },
         "required": ["command", "maxRetries", "retryDelay"]
        },
        "runTimeCheck": {
          "description": "Configuration for run-time liveness tests, which are performed periodically to verify that scaling group members are still operational.", 
          "type": "object",
          "properties": {
            "command": {  
              "description": "The command/script (executed over SSH) used to periodically verify that running servers in the pool are still up and running. A machine instance is considered live when the command is successful (zero exit code).", 
              "type": "string"
            },
            "period": {  
              "description": "The time (in seconds) between two successive liveness test runs.",
              "type": "number",
              "minimum": 1
            },
            "maxRetries": {
              "description": "The maximum number of attempts to run the liveness test before deeming an instance unhealthy.", 
              "type": "number",
              "minimum": 0
            },
            "retryDelay": {
              "description": "The delay (in seconds) between two successive liveness command retries.",
              "type": "number",
              "minimum": 0
            }
          },
         "required": ["command", "period", "maxRetries", "retryDelay"]
        }
      },
      "required": ["loginUser", "loginKey", "bootTimeCheck", "runTimeCheck"]
    },
    "alerts": {
      "description": "Optional configuration that describes how to send email alerts. If left out, alerts are disabled.",
      "type": "object",
      "properties": {
        "subject": {
          "description": "The subject line to use in sent mails (Subject).",
          "type": "string"
        },
        "recipients": {
          "description": "The receiver list (a list of recipient email addresses).",
          "type": "array",
          "items": { "type": "string", "format": "email" }            
        },
        "sender": {
          "description": "The sender email address to use in sent mails (From).",
          "type": "string",
          "format": "email"
        },
        "severityFilter": {
          "description": "A regular expression used to filter alerts. Alerts with a severity (one of DEBUG, INFO, NOTICE, WARN, ERROR, FATAL) that doesn't match the filter expression are suppressed and not sent. Default: '.*'",
          "type": "string"
        },        
        "mailServer": {
          "description": "Connection settings for the SMTP server through which emails are to be sent.",
          "type": "object",
          "properties": {
            "smtpHost": {
              "description": "SMTP server host name/IP address.",
              "type": "string"
            },
            "smtpPort": {
              "description": "SMTP server port. Default is 25.",
              "type": "number"
            },
            "authentication": {
              "description": "Optional username/password to authenticate with SMTP server. If left out, authentication is disabled.",
              "type": "object",
              "properties": {
                "userName": { "type": "string" },
                "password": { "type": "string" }
              },
              "required": ["userName", "password"]
            },
            "useSsl": {
              "description": "Enables/disables the use of SSL for SMTP connections. Default is false (disabled).",
              "type": "boolean"
            }
          },
          "required": ["smtpHost"]
        }
      },
      "required": ["subject", "recipients", "sender", "mailServer"]
    },
    "poolUpdatePeriod": {
      "description": "The time interval (in seconds) between periodical pool size updates. A pool size update may involve terminating termination-due instances and placing new spot requests to replace terminated spot requests. Default: 60.",
      "type": "number"
    }
  },
  "required": ["scalingGroup", "scaleUpConfig", "scaleDownConfig"]
}

=== Eeemil/scale.cloudpool/aws/autoscaling/src/test/resources/config/valid-awsasadapter-config.json
{
    "scalingGroup": {
      "name": "ec2-cluster",
      "config": {
        "awsAccessKeyId": "ABC",
        "awsSecretAccessKey": "XYZ",
        "region": "us-west-1"
      }
    },
    "scaleUpConfig": {
      "_comment": "These properties are specified in an AWS Launch Configuration for the Auto Scaling Group.",      
      "size": "N/A",
      "image": "N/A",
      "keyPair": "N/A",
      "securityGroups": [],
      "bootScript": []
    },
    "scaleDownConfig": {
      "victimSelectionPolicy": "OLDEST_INSTANCE",
      "instanceHourMargin": 600
    },
    "poolUpdatePeriod": 60            
}

=== Eeemil/scale.cloudpool/commons/src/test/resources/config/valid-cloudadapter-config-complete.json
{
    "scalingGroup": {
      "name": "my-scaling-group",
      "config": { 
        "keystoneEndpoint": "http://openstack.nova.com:5000/v2.0",
        "region": "RegionOne",
        "tenantName": "tenant",
        "userName": "clouduser",
        "password": "cloudpass"
      }      
    },
    "scaleUpConfig": {
      "size": "m1.small", 
      "image": "Ubuntu Server 12.04",
      "keyPair": "openstack_p11",
      "securityGroups": ["web"],               
      "bootScript": [
        "sudo apt-get update",
        "sudo apt-get install -y --force-yes apache2"
      ]
    },
    "scaleDownConfig": {
      "victimSelectionPolicy": "CLOSEST_TO_INSTANCE_HOUR",
      "instanceHourMargin": 0
    },
    "liveness": {
      "loginUser": "ubuntu",
      "loginKey": "src/test/resources/security/clientkey.pem",
      "bootTimeCheck": {
        "command": "sudo service apache2 status | grep 'is running'",
        "retryDelay": 20,
        "maxRetries": 15
      },
      "runTimeCheck": {      
        "command": "sudo service apache2 status | grep 'is running'",
        "period": 60,
        "maxRetries": 10,
        "retryDelay": 10
      }    
    },
    "alerts": {
      "subject": "[elastisys:scale] alert for scaling group 'my-scaling-group'",
      "recipients": ["recipient@elastisys.com"],
      "sender": "noreply@elastisys.com",
      "mailServer": {
        "smtpHost": "mail.elastisys.com",
        "smtpPort": 25,
        "authentication": {"userName": "user", "password": "password"},
        "useSsl": true
      }
    },    
    "poolUpdatePeriod": 180       
}

=== Eeemil/scale.cloudpool/aws/autoscaling/src/test/resources/config/valid-awsasadapter-config2.json
{
    "scalingGroup": {
      "name": "ec2-cluster",
      "config": {
        "awsAccessKeyId": "DEF",
        "awsSecretAccessKey": "TUV",
        "region": "us-east-1"
      }
    },
    "scaleUpConfig": {
      "_comment": "These properties are specified in an AWS Launch Configuration for the Auto Scaling Group.",      
      "size": "N/A",
      "image": "N/A",
      "keyPair": "N/A",
      "securityGroups": [],
      "bootScript": []
    },
    "scaleDownConfig": {
      "victimSelectionPolicy": "CLOSEST_TO_INSTANCE_HOUR",
      "instanceHourMargin": 300
    },
    "poolUpdatePeriod": 60            
}
